swagger: '2.0'
info:
  version: '1.0.0'
  title: Shopping Cart API
paths:
  /api/carts:
    get:
      summary: Retrieve all carts
      responses:
        200:
          description: A list of carts
    post:
      summary: Create a new cart
      responses:
        200:
          description: The newly created cart
  /api/carts/new:
    get:
      summary: Create a dummy cart (Admin only)
      security:
        - jwt: []
      responses:
        200:
          description: The newly created dummy cart
  /api/carts/{id}:
    get:
      summary: Get cart details by ID
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        200:
          description: Details of the requested cart
    put:
      summary: Update cart by ID
      parameters:
        - name: id
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
      responses:
        200:
          description: Updated cart details
  /api/carts/{cartId}/products/{productId}:
    put:
      summary: Update product in cart
      parameters:
        - name: cartId
          in: path
          required: true
          type: string
        - name: productId
          in: path
          required: true
          type: string
        - name: body
          in: body
          required: true
          schema:
            type: object
      responses:
        200:
          description: Updated cart with modified product
    delete:
      summary: Delete product from cart
      parameters:
        - name: cartId
          in: path
          required: true
          type: string
        - name: productId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Product deleted from cart
  /api/carts/{cartId}/addProduct/{productId}:
    post:
      summary: Add product to cart
      parameters:
        - name: cartId
          in: path
          required: true
          type: string
        - name: productId
          in: path
          required: true
          type: string
      security:
        - jwt: []
      responses:
        200:
          description: Product added to cart
  /api/carts/{cartId}:
    delete:
      summary: Delete cart by ID
      parameters:
        - name: cartId
          in: path
          required: true
          type: string
      responses:
        200:
          description: Cart deleted successfully
  /api/carts/{cartId}/purchase:
    get:
      summary: Initiate purchase process
      parameters:
        - name: cartId
          in: path
          required: true
          type: string
      security:
        - jwt: []
      responses:
        302:
          description: Redirect to payment checkout page


